required = [
]

[[override]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/coreos/go-oidc"

[[constraint]]
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "github.com/spf13/cobra"


